#!/bin/bash
   PATH=$PATH:$FEATURECOUNTS
   export PATH

counter=0
input="$DATA/listfilenames454.txt"
while IFS= read -r FILENAME
do
   counter=$((counter+1))
   PROJECTNAME=`echo $FILENAME | cut -c1-6`

   cd $BIO

   echo ' '
   echo '~~~~~~~~~~~~' $counter $PROJECTNAME 'FEATURECOUNTS ~~~~~~~~~~~~'

   featureCounts -a $GTF/CorkOak1.0_genomic.gtf -g gene_name -o 'counts'$PROJECTNAME'.txt' $BIO/$FILENAME'.bam' 2>&1 | tee -a $LOGS/'featurecountslog'$PROJECTNAME'.txt'

   cd ..
done < "$input"
